spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ""
            client-secret: "GOCSPX-"
logging:
  level:
    org.springframework.security: TRACE